/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.sistemabibliotecamusicalpresentacion;

import itson.sistemabibliotecamusicaldominio.AlbumDominio;
import itson.sistemabibliotecamusicaldominio.ArtistaDominio;
import itson.sistemabibliotecamusicaldominio.CancionDominio;
import itson.sistemabibliotecamusicaldominio.TipoFavoritoEnum;
import itson.sistemabibliotecamusicaldominio.UsuarioDominio;
import itson.sistemabibliotecamusicaldominio.dtos.ResultadosDTO;
import itson.sistemabibliotecamusicalnegocio.excepciones.NegocioException;
import itson.sistemabibliotecamusicalnegocio.fachada.IUsuarioFachada;
import itson.sistemabibliotecamusicalnegocio.fachada.implementaciones.UsuarioFachada;
import itson.sistemabibliotecamusicalpresentacion.utilidades.SesionUsuario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Camila Zubía
 */
public class PanelFavoritos extends javax.swing.JPanel {

    IUsuarioFachada usuarioFachada;
    UsuarioDominio usuario = SesionUsuario.getUsuario();
    private String tipoFiltroSeleccionado = "todo";
    
    /**
     * Creates new form PanelPerfil
     */
    public PanelFavoritos() {
        this.usuarioFachada = new UsuarioFachada();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnTodo = new javax.swing.JButton();
        txtFieldNombreUsuario = new javax.swing.JTextField();
        txtFieldCorreo = new javax.swing.JTextField();
        btnCanciones = new javax.swing.JButton();
        btnAlbumes = new javax.swing.JButton();
        btnArtistas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelListar = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtFieldBuscar = new javax.swing.JTextField();

        setBackground(new java.awt.Color(75, 28, 113));
        setMaximumSize(new java.awt.Dimension(1080, 648));
        setMinimumSize(new java.awt.Dimension(1080, 648));
        setPreferredSize(new java.awt.Dimension(1080, 648));

        PanelFondo.setBackground(new java.awt.Color(75, 28, 113));
        PanelFondo.setMaximumSize(new java.awt.Dimension(1080, 648));
        PanelFondo.setMinimumSize(new java.awt.Dimension(1080, 648));
        PanelFondo.setPreferredSize(new java.awt.Dimension(1080, 648));

        jPanel1.setBackground(new java.awt.Color(219, 182, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.darkGray));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(75, 28, 113));
        lblTitulo.setText("Favoritos");

        btnTodo.setBackground(new java.awt.Color(127, 76, 165));
        btnTodo.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnTodo.setForeground(new java.awt.Color(255, 255, 255));
        btnTodo.setText("Todo");
        btnTodo.setActionCommand("");
        btnTodo.setBorderPainted(false);
        btnTodo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodoActionPerformed(evt);
            }
        });

        txtFieldNombreUsuario.setEditable(false);
        txtFieldNombreUsuario.setBackground(new java.awt.Color(219, 182, 238));
        txtFieldNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtFieldNombreUsuario.setBorder(null);

        txtFieldCorreo.setEditable(false);
        txtFieldCorreo.setBackground(new java.awt.Color(219, 182, 238));
        txtFieldCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtFieldCorreo.setBorder(null);

        btnCanciones.setBackground(new java.awt.Color(127, 76, 165));
        btnCanciones.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnCanciones.setForeground(new java.awt.Color(255, 255, 255));
        btnCanciones.setText("Canciones");
        btnCanciones.setActionCommand("");
        btnCanciones.setBorderPainted(false);
        btnCanciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancionesActionPerformed(evt);
            }
        });

        btnAlbumes.setBackground(new java.awt.Color(127, 76, 165));
        btnAlbumes.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnAlbumes.setForeground(new java.awt.Color(255, 255, 255));
        btnAlbumes.setText("Albumes");
        btnAlbumes.setActionCommand("");
        btnAlbumes.setBorderPainted(false);
        btnAlbumes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAlbumes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlbumesActionPerformed(evt);
            }
        });

        btnArtistas.setBackground(new java.awt.Color(127, 76, 165));
        btnArtistas.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnArtistas.setForeground(new java.awt.Color(255, 255, 255));
        btnArtistas.setText("Artistas");
        btnArtistas.setActionCommand("");
        btnArtistas.setBorderPainted(false);
        btnArtistas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnArtistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtistasActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(219, 182, 238));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        panelListar.setBackground(new java.awt.Color(219, 182, 238));
        panelListar.setForeground(new java.awt.Color(0, 0, 0));
        panelListar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout panelListarLayout = new javax.swing.GroupLayout(panelListar);
        panelListar.setLayout(panelListarLayout);
        panelListarLayout.setHorizontalGroup(
            panelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        panelListarLayout.setVerticalGroup(
            panelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelListar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(btnCanciones)
                                .addGap(78, 78, 78)
                                .addComponent(btnAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(lblTitulo)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCanciones)
                            .addComponent(btnTodo)
                            .addComponent(btnArtistas)
                            .addComponent(btnAlbumes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(txtFieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(txtFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBuscar.setBackground(new java.awt.Color(127, 76, 165));
        btnBuscar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.setToolTipText("");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtFieldBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtFieldBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtFieldBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnBuscar)
                        .addGap(27, 27, 27)
                        .addComponent(txtFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(txtFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodoActionPerformed
        try {
            tipoFiltroSeleccionado = "todo";
            actualizarBotonesFiltro(btnTodo);
            List<ResultadosDTO> todo = usuarioFachada.listarFavoritos(usuario.getGenerosNoDeseados());
            cargarFavoritos(todo);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo filtrar por canciones");
        }
    }//GEN-LAST:event_btnTodoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
             buscarConParametros();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se pudo realizar la busqueda");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldBuscarActionPerformed

    }//GEN-LAST:event_txtFieldBuscarActionPerformed

    private void btnCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancionesActionPerformed
        try {
            tipoFiltroSeleccionado = "canciones";
            actualizarBotonesFiltro(btnCanciones);

            List<ResultadosDTO> canciones = usuarioFachada.listarFavoritosPorTipoYFiltro(TipoFavoritoEnum.CANCION, "", usuario.getGenerosNoDeseados());
            cargarFavoritos(canciones);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo filtrar por canciones");
        }
    }//GEN-LAST:event_btnCancionesActionPerformed

    private void btnAlbumesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlbumesActionPerformed
        try {
            tipoFiltroSeleccionado = "albumes";
            actualizarBotonesFiltro(btnCanciones);

            List<ResultadosDTO> albumes = usuarioFachada.listarFavoritosPorTipoYFiltro(TipoFavoritoEnum.ALBUM, "", usuario.getGenerosNoDeseados());
            cargarFavoritos(albumes);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo filtrar por albumes");
        }
    }//GEN-LAST:event_btnAlbumesActionPerformed

    private void btnArtistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtistasActionPerformed
        try {
            tipoFiltroSeleccionado = "artistas";
            actualizarBotonesFiltro(btnCanciones);

            List<ResultadosDTO> artistas = usuarioFachada.listarFavoritosPorTipoYFiltro(TipoFavoritoEnum.ARTISTA, "", usuario.getGenerosNoDeseados());
            cargarFavoritos(artistas);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo filtrar por artistas");
        }
    }//GEN-LAST:event_btnArtistasActionPerformed

    private void buscarConParametros() {
        String texto = txtFieldBuscar.getText().trim();

        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor introduce un texto para buscar.");
            return;
        }

        try {
            switch (tipoFiltroSeleccionado) {
                case "artistas" -> {
                    List<ResultadosDTO> artistas = usuarioFachada.listarFavoritosPorTipoYFiltro(TipoFavoritoEnum.ARTISTA, texto, usuario.getGenerosNoDeseados());
                    cargarFavoritos(artistas);
                }
                case "albumes" -> {
                    List<ResultadosDTO> albumes = usuarioFachada.listarFavoritosPorTipoYFiltro(TipoFavoritoEnum.ALBUM, texto, usuario.getGenerosNoDeseados());
                    cargarFavoritos(albumes);
                }
                case "canciones" -> {
                    List<ResultadosDTO> canciones = usuarioFachada.listarFavoritosPorTipoYFiltro(TipoFavoritoEnum.CANCION, texto, usuario.getGenerosNoDeseados());
                    cargarFavoritos(canciones);
                }
                default -> {
                    List<ResultadosDTO> todo = usuarioFachada.listarFavoritosPorFiltro(texto, usuario.getGenerosNoDeseados());
                    cargarFavoritos(todo);
                }
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "No se pudo realizar la busqueda");
        }
    }
    
    private void actualizarBotonesFiltro(javax.swing.JButton botonSeleccionado) {
        JButton[] botones = {btnTodo, btnArtistas, btnAlbumes, btnCanciones};

        for (JButton boton : botones) {
            if (boton == botonSeleccionado) {
                boton.setBackground(new Color(75, 28, 113));
                boton.setForeground(Color.WHITE);
            } else {
                boton.setBackground(new Color(127, 76, 165));
                boton.setForeground(Color.WHITE);
            }
        }
    }
    
    private void cargarFavoritos(List<?> registros) {
        try {
            JPanel panelInterno = new JPanel();
            panelInterno.setLayout(new BoxLayout(panelInterno, BoxLayout.Y_AXIS));

            for (Object o : registros) {
                JPanel panelElemento = new JPanel(new BorderLayout());
                panelElemento.setMaximumSize(new Dimension(700, 40));
                panelElemento.setBackground(Color.getHSBColor(219, 182, 238));

                JButton btnInfo = new JButton();
                JButton btnFavorito = new JButton("☆");

                btnInfo.setFont(new Font("Arial", Font.PLAIN, 14));
                panelElemento.add(btnInfo, BorderLayout.WEST);

                btnFavorito.setFocusPainted(false);
                btnFavorito.setForeground(Color.GRAY);

                switch (o) {
                    case ArtistaDominio artista -> {
                        btnInfo.setText(artista.getImagen() + artista.getNombre() + " - " + artista.getGenero());
                        btnInfo.addActionListener(e -> {
                            new ArtistaFrm().setVisible(true);
                            this.setVisible(false);
                        });
                        btnFavorito.addActionListener(e -> {
                            try {
                                if (usuarioFachada.esFavorito(artista.getId())) {
                                    usuarioFachada.eliminarFavorito(artista.getId());
                                    btnFavorito.setText("☆");
                                    btnFavorito.setForeground(Color.GRAY);
                                } else {
                                    try {
                                        usuarioFachada.agregarFavorito(artista.getId());
                                    } catch (NegocioException ex) {
                                        Logger.getLogger(PanelBuscar.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                    btnFavorito.setText("★️");
                                    btnFavorito.setForeground(Color.BLACK);
                                }
                            } catch (NegocioException ex) {
                                Logger.getLogger(PanelBuscar.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        });
                    }
                    case AlbumDominio album -> {
                        btnInfo.setText(album.getImagenPortada() + album.getNombre() + " - " + album.getGeneroMusical() + " (" + album.getFechaLanzamiento() + ")");
                        btnInfo.addActionListener(e -> {
                            new CancionesFrm().setVisible(true);
                            this.setVisible(false);
                        });
                        btnFavorito.addActionListener(e -> {
                            try {
                                if (usuarioFachada.esFavorito(album.getId())) {
                                    usuarioFachada.eliminarFavorito(album.getId());
                                    btnFavorito.setText("☆");
                                    btnFavorito.setForeground(Color.GRAY);
                                } else {
                                    usuarioFachada.agregarFavorito(album.getId());
                                    btnFavorito.setText("★️");
                                    btnFavorito.setForeground(Color.BLACK);
                                }
                            } catch (NegocioException ex) {
                                Logger.getLogger(PanelBuscar.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        });
                    }
                    case CancionDominio cancion -> {
                        btnInfo.setText(cancion.getNombre());
                        btnFavorito.addActionListener(e -> {
                            try {
                                if (usuarioFachada.esFavorito(cancion.getId())) {
                                    usuarioFachada.eliminarFavorito(cancion.getId());
                                    btnFavorito.setText("☆");
                                    btnFavorito.setForeground(Color.GRAY);
                                } else {
                                    usuarioFachada.agregarFavorito(cancion.getId());
                                    btnFavorito.setText("★️");
                                    btnFavorito.setForeground(Color.BLACK);
                                }
                            } catch (NegocioException ex) {
                                Logger.getLogger(PanelBuscar.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        });
                    }
                    default -> {
                        continue;
                    }
                }

                panelElemento.add(btnFavorito, BorderLayout.EAST);
                panelInterno.add(panelElemento);
            }
            panelListar.removeAll();
            panelListar.add(panelInterno);
            panelListar.revalidate();
            panelListar.repaint();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se pudo cargar el contenido de la biblioteca musical");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton btnAlbumes;
    private javax.swing.JButton btnArtistas;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCanciones;
    private javax.swing.JButton btnTodo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelListar;
    private javax.swing.JTextField txtFieldBuscar;
    private javax.swing.JTextField txtFieldCorreo;
    private javax.swing.JTextField txtFieldNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
