 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.sistemabibliotecamusicalpresentacion;

import itson.sistemabibliotecamusicaldominio.AlbumDominio;
import itson.sistemabibliotecamusicaldominio.ArtistaDominio;
import itson.sistemabibliotecamusicaldominio.CancionDominio;
import itson.sistemabibliotecamusicaldominio.dtos.ResultadosDTO;
import itson.sistemabibliotecamusicalnegocio.excepciones.NegocioException;
import itson.sistemabibliotecamusicalnegocio.fachada.IAlbumFachada;
import itson.sistemabibliotecamusicalnegocio.fachada.IArtistaFachada;
import itson.sistemabibliotecamusicalnegocio.fachada.ICancionFachada;
import itson.sistemabibliotecamusicalnegocio.fachada.implementaciones.AlbumFachada;
import itson.sistemabibliotecamusicalnegocio.fachada.implementaciones.ArtistaFachada;
import itson.sistemabibliotecamusicalnegocio.fachada.implementaciones.CancionFachada;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Camila Zubía
 */
public class PanelBuscar extends javax.swing.JPanel {

    IArtistaFachada artistaFachada;
    IAlbumFachada albumFachada;
    ICancionFachada cancionFachada;
    
    /**
     * Creates new form PanelPerfil
     */
    public PanelBuscar() {
        this.artistaFachada = new ArtistaFachada();
        this.albumFachada = new AlbumFachada();
        this.cancionFachada = new CancionFachada();
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnTodo = new javax.swing.JButton();
        btnCanciones = new javax.swing.JButton();
        btnAlbumes = new javax.swing.JButton();
        btnArtistas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelListar = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtFieldBuscar = new javax.swing.JTextField();

        setBackground(new java.awt.Color(75, 28, 113));
        setMaximumSize(new java.awt.Dimension(1080, 648));
        setMinimumSize(new java.awt.Dimension(1080, 648));
        setPreferredSize(new java.awt.Dimension(1080, 648));

        PanelFondo.setBackground(new java.awt.Color(75, 28, 113));
        PanelFondo.setMaximumSize(new java.awt.Dimension(1080, 648));
        PanelFondo.setMinimumSize(new java.awt.Dimension(1080, 648));
        PanelFondo.setPreferredSize(new java.awt.Dimension(1080, 648));

        jPanel1.setBackground(new java.awt.Color(219, 182, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.darkGray));

        btnTodo.setBackground(new java.awt.Color(127, 76, 165));
        btnTodo.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnTodo.setForeground(new java.awt.Color(255, 255, 255));
        btnTodo.setText("Todo");
        btnTodo.setActionCommand("");
        btnTodo.setBorderPainted(false);
        btnTodo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodoActionPerformed(evt);
            }
        });

        btnCanciones.setBackground(new java.awt.Color(127, 76, 165));
        btnCanciones.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnCanciones.setForeground(new java.awt.Color(255, 255, 255));
        btnCanciones.setText("Canciones");
        btnCanciones.setActionCommand("");
        btnCanciones.setBorderPainted(false);
        btnCanciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancionesActionPerformed(evt);
            }
        });

        btnAlbumes.setBackground(new java.awt.Color(127, 76, 165));
        btnAlbumes.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnAlbumes.setForeground(new java.awt.Color(255, 255, 255));
        btnAlbumes.setText("Albumes");
        btnAlbumes.setActionCommand("");
        btnAlbumes.setBorderPainted(false);
        btnAlbumes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAlbumes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlbumesActionPerformed(evt);
            }
        });

        btnArtistas.setBackground(new java.awt.Color(127, 76, 165));
        btnArtistas.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnArtistas.setForeground(new java.awt.Color(255, 255, 255));
        btnArtistas.setText("Artistas");
        btnArtistas.setActionCommand("");
        btnArtistas.setBorderPainted(false);
        btnArtistas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnArtistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtistasActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(219, 182, 238));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        panelListar.setBackground(new java.awt.Color(219, 182, 238));
        panelListar.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelListarLayout = new javax.swing.GroupLayout(panelListar);
        panelListar.setLayout(panelListarLayout);
        panelListarLayout.setHorizontalGroup(
            panelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        panelListarLayout.setVerticalGroup(
            panelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelListar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(btnCanciones)
                        .addGap(81, 81, 81)
                        .addComponent(btnAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTodo)
                    .addComponent(btnCanciones)
                    .addComponent(btnAlbumes)
                    .addComponent(btnArtistas))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        btnBuscar.setBackground(new java.awt.Color(127, 76, 165));
        btnBuscar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.setToolTipText("");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtFieldBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtFieldBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtFieldBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldBuscarActionPerformed(evt);
            }
        });
        txtFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnBuscar)
                        .addGap(27, 27, 27)
                        .addComponent(txtFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(txtFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodoActionPerformed
        try {
            List<ResultadosDTO> todo = artistaFachada.listarTodo();
            cargarBiblioteca(todo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se pudo filtrar por canciones");
        }
    }//GEN-LAST:event_btnTodoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se pudo realizar la busqueda");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldBuscarActionPerformed
        
    }//GEN-LAST:event_txtFieldBuscarActionPerformed

    private void btnCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancionesActionPerformed
        try {
            List<CancionDominio> canciones = cancionFachada.listarTodasLasCanciones();
            cargarBiblioteca(canciones);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo filtrar por canciones");
        }
    }//GEN-LAST:event_btnCancionesActionPerformed

    private void btnAlbumesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlbumesActionPerformed
        try {
            List<AlbumDominio> albumes = albumFachada.listarTodosLosAlbumes();
            cargarBiblioteca(albumes);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo filtrar por albumes");
        }
    }//GEN-LAST:event_btnAlbumesActionPerformed

    private void btnArtistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtistasActionPerformed
        try {
            List<ArtistaDominio> artistas = artistaFachada.listarTodosLosArtistas();
            cargarBiblioteca(artistas);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo filtrar por artistas");
        }
    }//GEN-LAST:event_btnArtistasActionPerformed

    private void txtFieldBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldBuscarKeyReleased
        
    }//GEN-LAST:event_txtFieldBuscarKeyReleased

    private void cargarBiblioteca(List<?> registros){
        try {
            panelListar.removeAll();
            panelListar.setLayout(new BoxLayout(this,BoxLayout.Y_AXIS));
            for(Object o : registros){
                JPanel panelElemento = new JPanel(new BorderLayout());
                panelElemento.setMaximumSize(new Dimension(700, 40));
                panelElemento.setBackground(Color.getHSBColor(219,182,238));

                JLabel lblInfo = new JLabel();
                JButton btnFavorito = new JButton("☆");
                
                if (o instanceof ArtistaDominio artista) {
                    lblInfo.setText(artista.getImagen() + artista.getNombre() + " - " + artista.getGenero());
                } else if (o instanceof AlbumDominio album) {
                    lblInfo.setText(album.getImagenPortada() + album.getNombre() + " - " + album.getGeneroMusical() + " (" + album.getFechaLanzamiento() + ")");
                } else if (o instanceof CancionDominio cancion) {
                    lblInfo.setText(cancion.getNombre());
                } else {
                    continue;
                }

                lblInfo.setFont(new Font("Arial", Font.PLAIN, 14));
                panelElemento.add(lblInfo, BorderLayout.WEST);
                
                btnFavorito.setFocusPainted(false);
                btnFavorito.setForeground(Color.GRAY);

                btnFavorito.addActionListener(e -> {
                    /**
                    if (favoritos.contains(obj)) {
                        favoritos.remove(obj);
                        btnFavorito.setText("☆");
                        btnFavorito.setForeground(Color.GRAY);
                    } else {
                        favoritos.add(obj);
                        btnFavorito.setText("★️");
                        btnFavorito.setForeground(Color.);
                    }
                    **/
                });

                panelElemento.add(btnFavorito, BorderLayout.EAST);
                panelListar.add(panelElemento);
            }

            panelListar.revalidate();
            panelListar.repaint();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se pudo cargar el contenido de la biblioteca musical");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton btnAlbumes;
    private javax.swing.JButton btnArtistas;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCanciones;
    private javax.swing.JButton btnTodo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelListar;
    private javax.swing.JTextField txtFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
