/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.sistemabibliotecamusicalpresentacion;

import itson.sistemabibliotecamusicaldominio.UsuarioDominio;
import itson.sistemabibliotecamusicaldominio.dtos.ModificarUsuarioDTO;
import itson.sistemabibliotecamusicalnegocio.excepciones.NegocioException;
import itson.sistemabibliotecamusicalnegocio.fachada.IUsuarioFachada;
import itson.sistemabibliotecamusicalnegocio.fachada.implementaciones.UsuarioFachada;
import itson.sistemabibliotecamusicalpresentacion.utilidades.SesionUsuario;
import java.awt.BorderLayout;
import java.awt.HeadlessException;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Camila Zubía
 */
public class PanelModificarPerfil extends javax.swing.JPanel {

    
    private final String PATRON_CORREO = "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$";
    private IUsuarioFachada usuarioFachada;
            
    public PanelModificarPerfil() {
        initComponents();
        cargarUsuario();
        this.usuarioFachada = new UsuarioFachada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnModificarPerfil = new javax.swing.JButton();
        lblNombreUsuario = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtFieldNombreUsuario = new javax.swing.JTextField();
        txtFieldCorreo = new javax.swing.JTextField();
        lblCorreo1 = new javax.swing.JLabel();
        txtFieldImagen = new javax.swing.JTextField();
        btnBuscarArchivo = new javax.swing.JButton();

        setBackground(new java.awt.Color(75, 28, 113));
        setMaximumSize(new java.awt.Dimension(1080, 648));
        setMinimumSize(new java.awt.Dimension(1080, 648));
        setPreferredSize(new java.awt.Dimension(1080, 648));

        PanelFondo.setBackground(new java.awt.Color(75, 28, 113));
        PanelFondo.setMaximumSize(new java.awt.Dimension(1000, 550));
        PanelFondo.setMinimumSize(new java.awt.Dimension(1000, 550));
        PanelFondo.setPreferredSize(new java.awt.Dimension(1000, 550));

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(219, 182, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.darkGray));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(75, 28, 113));
        lblTitulo.setText("Modificar perfil");

        btnModificarPerfil.setBackground(new java.awt.Color(127, 76, 165));
        btnModificarPerfil.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnModificarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarPerfil.setText("Modificar perfil");
        btnModificarPerfil.setBorderPainted(false);
        btnModificarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPerfilActionPerformed(evt);
            }
        });

        lblNombreUsuario.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreUsuario.setText("Nombre de usuario:");

        lblCorreo.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreo.setText("Correo:");

        txtFieldNombreUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtFieldNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtFieldNombreUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtFieldCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtFieldCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtFieldCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCorreo1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblCorreo1.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreo1.setText("Imagen de perfil:");

        txtFieldImagen.setBackground(new java.awt.Color(255, 255, 255));
        txtFieldImagen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtFieldImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBuscarArchivo.setBackground(new java.awt.Color(75, 28, 113));
        btnBuscarArchivo.setText("Buscar...");
        btnBuscarArchivo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreUsuario)
                                    .addComponent(lblCorreo)
                                    .addComponent(lblCorreo1))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(btnModificarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(txtFieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(txtFieldImagen)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitulo)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreUsuario)
                    .addComponent(txtFieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblCorreo)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo1)
                    .addComponent(txtFieldImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(btnModificarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 109, Short.MAX_VALUE)
                .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPerfilActionPerformed
        try{
            if(!validarCampos()) return;
            
            ModificarUsuarioDTO usuarioModificado = construirModificarUsuarioDTO();
            UsuarioDominio usuario = usuarioFachada.modificarUsuario(usuarioModificado);
            
            SesionUsuario.iniciarSesion(usuario);
            JOptionPane.showMessageDialog(this, "Usuario modificado con éxito.");
            
            abrirPanelPerfil();
        }catch(NegocioException | HeadlessException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);            
        }
    }//GEN-LAST:event_btnModificarPerfilActionPerformed

    private void btnBuscarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarArchivoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecciona una imagen");

        // Filtro para que solo muestre imágenes
        FileNameExtensionFilter filtro = new FileNameExtensionFilter(
            "Imágenes (JPG, PNG, GIF)", "jpg", "jpeg", "png", "gif"
        );
        fileChooser.setFileFilter(filtro);

        int resultado = fileChooser.showOpenDialog(null);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            String ruta = archivoSeleccionado.getAbsolutePath();
            txtFieldImagen.setText(ruta); // Copia la ruta al textfield
        }
    }//GEN-LAST:event_btnBuscarArchivoActionPerformed

    private void cargarUsuario(){
        UsuarioDominio usuario = SesionUsuario.getUsuario();
        txtFieldImagen.setColumns(20);
        if(usuario != null){
            txtFieldNombreUsuario.setText(usuario.getNombreUsuario());
            txtFieldCorreo.setText(usuario.getCorreo());
            txtFieldImagen.setText(usuario.getImagen());
        }
    }
    
    private ModificarUsuarioDTO construirModificarUsuarioDTO (){
        ModificarUsuarioDTO usuarioModificado = new ModificarUsuarioDTO();
        usuarioModificado.setId(SesionUsuario.getUsuario().getId());
        usuarioModificado.setNombre(txtFieldNombreUsuario.getText());
        usuarioModificado.setCorreo(txtFieldCorreo.getText());
        usuarioModificado.setImagen(txtFieldImagen.getText());
        return usuarioModificado;
    }
    
    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Validacion", JOptionPane.WARNING_MESSAGE);
    }
    
    private boolean validarCampos() throws NegocioException{
        if (!validarNombreUsuario()){
            return false;
        }
        if (!validarCorreo()){
            return false;
        }
        return true;
    }
    
    private boolean validarNombreUsuario() throws NegocioException{
        if (txtFieldNombreUsuario.getText().trim().isEmpty()) {
            mostrarError("El nombre del usuario es obligatorio.");
            return false;
        }
        if(txtFieldNombreUsuario.getText().contains(" ")){
            mostrarError("El nombre de usuario no puede contener espacios");
            return false;
        }
        if(txtFieldNombreUsuario.getText().length() > 30){
            mostrarError("El nombre de usuario no debe superar los 30 caracteres.");
            return false;
        }
        return true;
    }
    
    private boolean validarCorreo(){
        if(txtFieldCorreo.getText().trim().isEmpty()){
            mostrarError("El correo es obligatorio.");
            return false;
        }
        if(txtFieldCorreo.getText().contains(" ")){
            mostrarError("El correo no puede contener espacios.");
            return false;
        }
        if (!txtFieldCorreo.getText().matches(PATRON_CORREO)){
            mostrarError("El correo es inválido.");
            return false;
        }
        return true;
    }

    private void abrirPanelPerfil() {
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        PanelPerfil panelAnterior = new PanelPerfil();

        frame.getContentPane().removeAll();
        frame.getContentPane().add(panelAnterior, BorderLayout.CENTER);
        frame.revalidate();
        frame.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton btnBuscarArchivo;
    private javax.swing.JButton btnModificarPerfil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtFieldCorreo;
    private javax.swing.JTextField txtFieldImagen;
    private javax.swing.JTextField txtFieldNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
