/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.sistemabibliotecamusicalpresentacion;

import itson.sistemabibliotecamusicaldominio.AlbumDominio;
import itson.sistemabibliotecamusicaldominio.CancionDominio;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author saula
 */
public class PanelAlbum extends javax.swing.JPanel {

    private AlbumDominio album;

    public PanelAlbum(AlbumDominio album) {
        initComponents();
        this.album = album;
        SwingUtilities.invokeLater(() -> cargarImagenAlbum());
        SwingUtilities.invokeLater(() -> cargarInfoAlbum());
        SwingUtilities.invokeLater(() -> cargarCanciones());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        contenedorPnl = new javax.swing.JPanel();
        panelImagenAlbum = new javax.swing.JPanel();
        panelInfoAlbum = new javax.swing.JPanel();
        panelCanciones = new javax.swing.JPanel();

        jPanel2.setBackground(new java.awt.Color(75, 28, 113));

        contenedorPnl.setBackground(new java.awt.Color(219, 182, 238));
        contenedorPnl.setPreferredSize(new java.awt.Dimension(980, 548));

        panelImagenAlbum.setBackground(new java.awt.Color(215, 161, 220));
        panelImagenAlbum.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelImagenAlbumLayout = new javax.swing.GroupLayout(panelImagenAlbum);
        panelImagenAlbum.setLayout(panelImagenAlbumLayout);
        panelImagenAlbumLayout.setHorizontalGroup(
            panelImagenAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );
        panelImagenAlbumLayout.setVerticalGroup(
            panelImagenAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        panelInfoAlbum.setBackground(new java.awt.Color(215, 161, 220));
        panelInfoAlbum.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelInfoAlbumLayout = new javax.swing.GroupLayout(panelInfoAlbum);
        panelInfoAlbum.setLayout(panelInfoAlbumLayout);
        panelInfoAlbumLayout.setHorizontalGroup(
            panelInfoAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );
        panelInfoAlbumLayout.setVerticalGroup(
            panelInfoAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelCanciones.setBackground(new java.awt.Color(215, 161, 220));
        panelCanciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelCancionesLayout = new javax.swing.GroupLayout(panelCanciones);
        panelCanciones.setLayout(panelCancionesLayout);
        panelCancionesLayout.setHorizontalGroup(
            panelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCancionesLayout.setVerticalGroup(
            panelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout contenedorPnlLayout = new javax.swing.GroupLayout(contenedorPnl);
        contenedorPnl.setLayout(contenedorPnlLayout);
        contenedorPnlLayout.setHorizontalGroup(
            contenedorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorPnlLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(contenedorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelCanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contenedorPnlLayout.createSequentialGroup()
                        .addComponent(panelImagenAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelInfoAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        contenedorPnlLayout.setVerticalGroup(
            contenedorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorPnlLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(contenedorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelImagenAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInfoAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panelCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(contenedorPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 1006, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(contenedorPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void cargarImagenAlbum() {
        panelImagenAlbum.removeAll();
        ImageIcon icono = new ImageIcon(this.album.getImagenPortada());
        Image imagenEscalada = icono.getImage().getScaledInstance(
                panelImagenAlbum.getWidth(), panelImagenAlbum.getHeight(), Image.SCALE_SMOOTH);
        JLabel lblImagen = new JLabel(new ImageIcon(imagenEscalada));
        panelImagenAlbum.setLayout(new BorderLayout());
        panelImagenAlbum.add(lblImagen, BorderLayout.CENTER);
        panelImagenAlbum.revalidate();
        panelImagenAlbum.repaint();
    }

    private void cargarInfoAlbum() {
        panelInfoAlbum.removeAll();
        panelInfoAlbum.setLayout(new BoxLayout(panelInfoAlbum, BoxLayout.Y_AXIS));

        panelInfoAlbum.add(new JLabel("Nombre: " + this.album.getNombre()));
        
        panelInfoAlbum.add(new JLabel("Género: " + this.album.getGeneroMusical()));

        panelInfoAlbum.revalidate();
        panelInfoAlbum.repaint();
    }
    
    private void cargarCanciones(){
        panelCanciones.removeAll();
        panelCanciones.setLayout(new BoxLayout(panelCanciones, BoxLayout.Y_AXIS));
        for (CancionDominio cancion : this.album.getCanciones()){
            JPanel panelCancion = new JPanel(new BorderLayout());
            panelCancion.setBorder(BorderFactory.createLineBorder(Color.GRAY));
            panelCancion.setMaximumSize(new Dimension(Integer.MAX_VALUE, 100));

            // Imagen del álbum
            ImageIcon icono = new ImageIcon(cancion.getImagenCancion());
            Image imagen = icono.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH);
            JLabel lblImagen = new JLabel(new ImageIcon(imagen));
            panelCancion.add(lblImagen, BorderLayout.WEST);

            // Info del álbum
            JPanel info = new JPanel(new GridLayout(2, 1));
            info.add(new JLabel("Nombre: " + cancion.getNombre()));
            panelCancion.add(info, BorderLayout.CENTER);

            // Evento al hacer clic
            panelCancion.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    mostrarPanelCancion(cancion);
                }
            });
            panelCanciones.add(panelCancion);
        }
        panelCanciones.revalidate();
        panelCanciones.repaint();
    }
    
    private void mostrarPanelCancion(CancionDominio cancion){
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        PanelCancion panel = new PanelCancion(cancion);

        frame.getContentPane().removeAll();
        frame.getContentPane().add(panel, BorderLayout.CENTER);
        frame.revalidate();
        frame.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorPnl;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelCanciones;
    private javax.swing.JPanel panelImagenAlbum;
    private javax.swing.JPanel panelInfoAlbum;
    // End of variables declaration//GEN-END:variables
}
