/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.sistemabibliotecamusicalpresentacion;

import itson.sistemabibliotecamusicaldominio.ArtistaDominio;
import itson.sistemabibliotecamusicaldominio.IntegranteDominio;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Image;
import java.time.format.DateTimeFormatter;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author saula
 */
public class PanelIntegrantesHistorico extends javax.swing.JPanel {

    private ArtistaDominio artista;
    
    public PanelIntegrantesHistorico(ArtistaDominio artista) {
        initComponents();
        this.artista = artista;
        SwingUtilities.invokeLater(() -> cargarImagenArtista());
        SwingUtilities.invokeLater(() -> cargarInfoArtista());
        SwingUtilities.invokeLater(() -> cargarIntegrantes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        contenedorPnl = new javax.swing.JPanel();
        panelImagenArtista = new javax.swing.JPanel();
        panelInfoArtista = new javax.swing.JPanel();
        panelIntegrantes = new javax.swing.JPanel();

        jPanel2.setBackground(new java.awt.Color(75, 28, 113));

        contenedorPnl.setBackground(new java.awt.Color(219, 182, 238));
        contenedorPnl.setPreferredSize(new java.awt.Dimension(980, 548));

        panelImagenArtista.setBackground(new java.awt.Color(215, 161, 220));
        panelImagenArtista.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelImagenArtistaLayout = new javax.swing.GroupLayout(panelImagenArtista);
        panelImagenArtista.setLayout(panelImagenArtistaLayout);
        panelImagenArtistaLayout.setHorizontalGroup(
            panelImagenArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );
        panelImagenArtistaLayout.setVerticalGroup(
            panelImagenArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelInfoArtista.setBackground(new java.awt.Color(215, 161, 220));
        panelInfoArtista.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelInfoArtistaLayout = new javax.swing.GroupLayout(panelInfoArtista);
        panelInfoArtista.setLayout(panelInfoArtistaLayout);
        panelInfoArtistaLayout.setHorizontalGroup(
            panelInfoArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );
        panelInfoArtistaLayout.setVerticalGroup(
            panelInfoArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        panelIntegrantes.setBackground(new java.awt.Color(215, 161, 220));
        panelIntegrantes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelIntegrantesLayout = new javax.swing.GroupLayout(panelIntegrantes);
        panelIntegrantes.setLayout(panelIntegrantesLayout);
        panelIntegrantesLayout.setHorizontalGroup(
            panelIntegrantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelIntegrantesLayout.setVerticalGroup(
            panelIntegrantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout contenedorPnlLayout = new javax.swing.GroupLayout(contenedorPnl);
        contenedorPnl.setLayout(contenedorPnlLayout);
        contenedorPnlLayout.setHorizontalGroup(
            contenedorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorPnlLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(contenedorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelIntegrantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contenedorPnlLayout.createSequentialGroup()
                        .addComponent(panelImagenArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelInfoArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        contenedorPnlLayout.setVerticalGroup(
            contenedorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorPnlLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(contenedorPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelImagenArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInfoArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panelIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(contenedorPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 1006, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(contenedorPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cargarImagenArtista(){
        panelImagenArtista.removeAll();
        ImageIcon icono = new ImageIcon(this.artista.getImagen());
        Image imagenEscalada = icono.getImage().getScaledInstance(
                panelImagenArtista.getWidth(), panelImagenArtista.getHeight(), Image.SCALE_SMOOTH);
        JLabel lblImagen = new JLabel(new ImageIcon(imagenEscalada));
        panelImagenArtista.setLayout(new BorderLayout());
        panelImagenArtista.add(lblImagen, BorderLayout.CENTER);
        panelImagenArtista.revalidate();
        panelImagenArtista.repaint();
    }

    private void cargarInfoArtista(){
        panelInfoArtista.removeAll();
        panelInfoArtista.setLayout(new BoxLayout(panelInfoArtista, BoxLayout.Y_AXIS));

        panelInfoArtista.add(new JLabel("Nombre: " + this.artista.getNombre()));

        String tipo;
        if (this.artista.isEsBanda()) {
            tipo = "Banda";
        } else {
            tipo = "Solista";
        }

        panelInfoArtista.add(new JLabel("Tipo: " + tipo));
        panelInfoArtista.add(new JLabel("Género: " + this.artista.getGenero()));

        panelInfoArtista.revalidate();
        panelInfoArtista.repaint();
    }

    private void cargarIntegrantes() {
        panelIntegrantes.removeAll();
        panelIntegrantes.setLayout(new BoxLayout(panelIntegrantes, BoxLayout.Y_AXIS));

        JLabel titulo = new JLabel("Histórico de Integrantes:");
        titulo.setFont(new Font("Arial", Font.BOLD, 16));
        panelIntegrantes.add(titulo);

        for (IntegranteDominio integrante : artista.getIntegrantes()) {
            String fechaSalida;
            if(integrante.getFechaSalida() == null){
                fechaSalida = "";
            }else{
                fechaSalida = integrante.getFechaSalida().format(DateTimeFormatter.ISO_DATE);
            }
            JPanel panelIntegrante = new JPanel(new FlowLayout(FlowLayout.LEFT));
            panelIntegrante.add(new JLabel("• " + integrante.getNombre()
                    + " - " + integrante.getRol()
                    + " - " + integrante.getFechaIngreso()
                    + " - " + fechaSalida));
            panelIntegrantes.add(panelIntegrante);

        }

        panelIntegrantes.revalidate();
        panelIntegrantes.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorPnl;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelImagenArtista;
    private javax.swing.JPanel panelInfoArtista;
    private javax.swing.JPanel panelIntegrantes;
    // End of variables declaration//GEN-END:variables
}
