/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.sistemabibliotecamusicalpresentacion;

import itson.sistemabibliotecamusicaldominio.UsuarioDominio;
import itson.sistemabibliotecamusicalpresentacion.utilidades.SesionUsuario;
import java.awt.BorderLayout;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Camila Zubía
 */
public class PanelPerfil extends javax.swing.JPanel {
    
    

    /**
     * Creates new form PanelPerfil
     */
    public PanelPerfil() {
        initComponents();
        SwingUtilities.invokeLater(() -> cargarUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelFotoPerfil = new javax.swing.JPanel();
        btnModificarPerfil = new javax.swing.JButton();
        lblNombreUsuario = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtFieldNombreUsuario = new javax.swing.JTextField();
        txtFieldCorreo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(75, 28, 113));
        setMaximumSize(new java.awt.Dimension(1080, 648));
        setMinimumSize(new java.awt.Dimension(1080, 648));
        setPreferredSize(new java.awt.Dimension(1080, 648));

        PanelFondo.setBackground(new java.awt.Color(75, 28, 113));
        PanelFondo.setMaximumSize(new java.awt.Dimension(1080, 648));
        PanelFondo.setMinimumSize(new java.awt.Dimension(1080, 648));
        PanelFondo.setPreferredSize(new java.awt.Dimension(1080, 648));

        jPanel1.setBackground(new java.awt.Color(219, 182, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.darkGray));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(75, 28, 113));
        lblTitulo.setText("Perfil");

        panelFotoPerfil.setBackground(new java.awt.Color(219, 182, 238));
        panelFotoPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelFotoPerfilLayout = new javax.swing.GroupLayout(panelFotoPerfil);
        panelFotoPerfil.setLayout(panelFotoPerfilLayout);
        panelFotoPerfilLayout.setHorizontalGroup(
            panelFotoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        panelFotoPerfilLayout.setVerticalGroup(
            panelFotoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );

        btnModificarPerfil.setBackground(new java.awt.Color(127, 76, 165));
        btnModificarPerfil.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnModificarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarPerfil.setText("Modificar perfil");
        btnModificarPerfil.setBorderPainted(false);
        btnModificarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPerfilActionPerformed(evt);
            }
        });

        lblNombreUsuario.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreUsuario.setText("Nombre de usuario:");

        lblCorreo.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreo.setText("Correo:");

        txtFieldNombreUsuario.setEditable(false);
        txtFieldNombreUsuario.setBackground(new java.awt.Color(219, 182, 238));
        txtFieldNombreUsuario.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtFieldNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtFieldNombreUsuario.setBorder(null);

        txtFieldCorreo.setEditable(false);
        txtFieldCorreo.setBackground(new java.awt.Color(219, 182, 238));
        txtFieldCorreo.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtFieldCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtFieldCorreo.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(panelFotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnModificarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCorreo)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblNombreUsuario)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 141, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(lblTitulo)))
                .addGap(208, 208, 208))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btnModificarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(panelFotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreUsuario)
                    .addComponent(txtFieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(txtFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondoLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPerfilActionPerformed
        abrirPanelModificar();
    }//GEN-LAST:event_btnModificarPerfilActionPerformed

    private void cargarUsuario(){
        UsuarioDominio usuario = SesionUsuario.getUsuario();
        if(usuario != null){
            txtFieldNombreUsuario.setText(usuario.getNombreUsuario());
            txtFieldCorreo.setText(usuario.getCorreo());
            if (usuario.getImagen() != null && !usuario.getImagen().isBlank()) {
                File imagen = new File(usuario.getImagen().trim());
                if (imagen.exists()) {
                    ImageIcon icono = new ImageIcon(imagen.getAbsolutePath());
                    Image imagenEscalada = icono.getImage().getScaledInstance(
                            panelFotoPerfil.getWidth(), panelFotoPerfil.getHeight(), Image.SCALE_SMOOTH
                    );
                    panelFotoPerfil.setLayout(new BorderLayout());
                    panelFotoPerfil.removeAll();
                    panelFotoPerfil.add(new JLabel(new ImageIcon(imagenEscalada)), BorderLayout.CENTER);
                    panelFotoPerfil.revalidate();
                    panelFotoPerfil.repaint();
                }
            }
        }
    }
    
    public void abrirPanelModificar() {
        try {
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            PanelModificarPerfil panel = new PanelModificarPerfil();

            frame.getContentPane().removeAll();
            frame.getContentPane().add(panel, BorderLayout.CENTER);
            frame.revalidate();
            frame.repaint();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar la siguiente ventana: " + ex.getMessage());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton btnModificarPerfil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelFotoPerfil;
    private javax.swing.JTextField txtFieldCorreo;
    private javax.swing.JTextField txtFieldNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
