/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.sistemabibliotecamusicalpresentacion;

import itson.sistemabibliotecamusicaldominio.UsuarioDominio;
import itson.sistemabibliotecamusicaldominio.dtos.RegistrarUsuarioDTO;
import itson.sistemabibliotecamusicalnegocio.excepciones.NegocioException;
import itson.sistemabibliotecamusicalnegocio.fachada.IUsuarioFachada;
import itson.sistemabibliotecamusicalnegocio.fachada.implementaciones.UsuarioFachada;
import java.awt.HeadlessException;
import java.io.File;
import java.util.Arrays;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author saula
 */
public class RegistrarUsuarioFrm extends javax.swing.JFrame {

    private final String PATRON_CORREO = "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$";
    private final IUsuarioFachada usuarioFachada;
    
    public RegistrarUsuarioFrm() {
        initComponents();
        this.usuarioFachada = new UsuarioFachada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelContenedor = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        lblRegistrarse = new javax.swing.JLabel();
        panelnformacion = new javax.swing.JPanel();
        lblCorreo = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        passwordConfirmarContraseña = new javax.swing.JPasswordField();
        txtCorreo = new javax.swing.JTextField();
        passwordContraseña = new javax.swing.JPasswordField();
        lblConfirmarContraseña = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtUrlImagen = new javax.swing.JTextField();
        lblSeleccionarImagen = new javax.swing.JLabel();
        btnBuscarArchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(75, 28, 113));

        panelContenedor.setBackground(new java.awt.Color(219, 182, 238));
        panelContenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.darkGray));

        btnRegistrar.setBackground(new java.awt.Color(127, 76, 165));
        btnRegistrar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblRegistrarse.setBackground(new java.awt.Color(255, 255, 255));
        lblRegistrarse.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        lblRegistrarse.setForeground(new java.awt.Color(75, 28, 113));
        lblRegistrarse.setText("Registrarse");

        panelnformacion.setBackground(new java.awt.Color(219, 182, 238));

        lblCorreo.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(75, 28, 113));
        lblCorreo.setText("Correo:");

        lblNombreUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(75, 28, 113));
        lblNombreUsuario.setText("Nombre de usuario:");

        txtNombreUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNombreUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        passwordConfirmarContraseña.setBackground(new java.awt.Color(255, 255, 255));
        passwordConfirmarContraseña.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passwordConfirmarContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        passwordContraseña.setBackground(new java.awt.Color(255, 255, 255));
        passwordContraseña.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passwordContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblConfirmarContraseña.setBackground(new java.awt.Color(255, 255, 255));
        lblConfirmarContraseña.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblConfirmarContraseña.setForeground(new java.awt.Color(75, 28, 113));
        lblConfirmarContraseña.setText("Confirmar contraseña:");

        lblContraseña.setBackground(new java.awt.Color(255, 255, 255));
        lblContraseña.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(75, 28, 113));
        lblContraseña.setText("Contraseña:");

        txtUrlImagen.setBackground(new java.awt.Color(255, 255, 255));
        txtUrlImagen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtUrlImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSeleccionarImagen.setBackground(new java.awt.Color(255, 255, 255));
        lblSeleccionarImagen.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblSeleccionarImagen.setForeground(new java.awt.Color(75, 28, 113));
        lblSeleccionarImagen.setText("Seleccionar imagen:");

        btnBuscarArchivo.setBackground(new java.awt.Color(75, 28, 113));
        btnBuscarArchivo.setText("Buscar...");
        btnBuscarArchivo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelnformacionLayout = new javax.swing.GroupLayout(panelnformacion);
        panelnformacion.setLayout(panelnformacionLayout);
        panelnformacionLayout.setHorizontalGroup(
            panelnformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelnformacionLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelnformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCorreo)
                    .addComponent(lblContraseña)
                    .addComponent(lblNombreUsuario))
                .addGap(18, 18, 18)
                .addGroup(panelnformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelnformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(passwordContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelnformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelnformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelnformacionLayout.createSequentialGroup()
                        .addComponent(lblConfirmarContraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passwordConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelnformacionLayout.createSequentialGroup()
                        .addComponent(lblSeleccionarImagen)
                        .addGap(18, 18, 18)
                        .addComponent(txtUrlImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 23, Short.MAX_VALUE))
        );
        panelnformacionLayout.setVerticalGroup(
            panelnformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelnformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelnformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreUsuario)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelnformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorreo))
                .addGap(18, 18, 18)
                .addGroup(panelnformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContraseña)
                    .addComponent(passwordContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelnformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirmarContraseña)
                    .addComponent(passwordConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelnformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelnformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUrlImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarArchivo))
                    .addComponent(lblSeleccionarImagen))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenedorLayout.createSequentialGroup()
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(352, 352, 352))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenedorLayout.createSequentialGroup()
                        .addComponent(lblRegistrarse)
                        .addGap(260, 260, 260))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenedorLayout.createSequentialGroup()
                        .addComponent(panelnformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184))))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistrarse)
                .addGap(41, 41, 41)
                .addComponent(panelnformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try{
            if (!validarCampos()) return;
            
            RegistrarUsuarioDTO usuarioRegistrar = construirNuevoUsuario();
            UsuarioDominio nuevoUsuario = usuarioFachada.registrarUsuario(usuarioRegistrar);
            
            JOptionPane.showMessageDialog(this, "Usuario creado con éxito.");
            
            limpiarCampos();
            new InicioSesionFrm().setVisible(true);
            this.dispose();
            
        }catch(NegocioException | HeadlessException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarArchivoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecciona una imagen");

        // Filtro para que solo muestre imágenes
        FileNameExtensionFilter filtro = new FileNameExtensionFilter(
            "Imágenes (JPG, PNG, GIF)", "jpg", "jpeg", "png", "gif"
        );
        fileChooser.setFileFilter(filtro);

        int resultado = fileChooser.showOpenDialog(null);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            String ruta = archivoSeleccionado.getAbsolutePath();
            txtUrlImagen.setText(ruta); // Copia la ruta al textfield
        }
    }//GEN-LAST:event_btnBuscarArchivoActionPerformed

    private boolean validarCampos() throws NegocioException {
        if (!validarNombreUsuario())
            return false;
        if (!validarCorreo())
            return false;
        if (!verificarCoincidenciaContrasenas()) {
            return false;
        }
        char[] contrasenia = passwordContraseña.getPassword();
        if (contrasenia.length < 6) {
            mostrarError("La contraseña debe tener al menos 6 caracteres.");
            return false;
        }
        return true;
    }

    private boolean verificarCoincidenciaContrasenas(){
        char[] contrasena1 = passwordContraseña.getPassword();
        char[] contrasena2 = passwordConfirmarContraseña.getPassword();
        if(!Arrays.equals(contrasena1, contrasena2)){
            mostrarError("Las contraseñas no coinciden.");
            return false;
        } 
        return true;
    }

    private boolean validarCorreo(){
        if(txtCorreo.getText().trim().isEmpty()){
            mostrarError("El correo es obligatorio.");
            return false;
        }
        if(txtCorreo.getText().contains(" ")){
            mostrarError("El correo no puede contener espacios.");
            return false;
        }
        if (!txtCorreo.getText().matches(PATRON_CORREO)){
            mostrarError("El correo es inválido.");
            return false;
        }
        return true;
    }
 
    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Validacion", JOptionPane.WARNING_MESSAGE);
    }

    private RegistrarUsuarioDTO construirNuevoUsuario(){
        RegistrarUsuarioDTO nuevoUsuario = new RegistrarUsuarioDTO();
        nuevoUsuario.setUsuario(txtNombreUsuario.getText());
        nuevoUsuario.setCorreo(txtCorreo.getText());
        nuevoUsuario.setContrasenia(passwordContraseña.getPassword());
        nuevoUsuario.setImagen(txtUrlImagen.getText());
        return nuevoUsuario;
    }
    
    private void limpiarCampos(){
        txtNombreUsuario.setText("");
        txtCorreo.setText("");
        txtUrlImagen.setText("");
        passwordContraseña.setText("");
        passwordConfirmarContraseña.setText("");
    }
    
    private boolean validarNombreUsuario() throws NegocioException{
        if (txtNombreUsuario.getText().trim().isEmpty()) {
            mostrarError("El nombre del usuario es obligatorio.");
            return false;
        }
        if(txtNombreUsuario.getText().contains(" ")){
            mostrarError("El nombre de usuario no puede contener espacios");
            return false;
        }
        if(txtNombreUsuario.getText().length() > 30){
            mostrarError("El nombre de usuario no debe superar los 30 caracteres.");
            return false;
        }
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarArchivo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblConfirmarContraseña;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblRegistrarse;
    private javax.swing.JLabel lblSeleccionarImagen;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelnformacion;
    private javax.swing.JPasswordField passwordConfirmarContraseña;
    private javax.swing.JPasswordField passwordContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtUrlImagen;
    // End of variables declaration//GEN-END:variables
}
